name: Update repository
on:
  workflow_dispatch:
  schedule:
    - cron: 37 * * * *
jobs:
  # This workflow contains a single job called "update"
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt install nodejs npm -y -qq
          npm i node-fetch

      - name: Update apps.json
        run: |
          node update-apps.js https://apps.altstore.io ./news.json ./apps.json https://asdfugil.github.io/altstore-beta
      - name: Commit & push changes
        run: |
          git config --global user.name "AltStore Beta"
          git config --global user.email actions@github.com
          git add apps.json package-lock.json
          git commit -am "Update apps"
          git push
